import type { Metadata } from "next";
import "./globals.css";
import { NavigationMenu } from "@/components/layout/navbar";
import { Press_Start_2P } from "next/font/google";
import Header from "@/components/layout/game-header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pressStart2P = Press_Start_2P({
  weight: '400', // Press Start 2P typically comes in one weight
  subsets: ['latin'],
  variable: '--font-press-start-2p', // Define a CSS variable for the font
  display: 'swap', // Optimize font loading
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${pressStart2P.variable} bg-[#070d1f] text-white`}>
        {children}
        <NavigationMenu />
      </body>
    </html>
  );
}
